

services:
  back:
    env_file:
      - ./back/.env
    image: sistemapresenca-back:latest
    pull_policy: never
    volumes:
      - back_static:/app/staticfiles
      - ./docker/back_entrypoint.sh:/app/back_entrypoint.sh
      - ./db.sqlite3:/app/db.sqlite3

  front:
    image: sistemapresenca-front:latest
    pull_policy: never
    volumes:
      - ./front_build:/mnt/front
    depends_on:
      - back

  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
      - "8000:8000"
      - "3000:3000"
    volumes:
      - ./docker/Caddyfile:/etc/caddy/Caddyfile
      - back_static:/app/staticfiles
      - ./front_build:/app/front

volumes:
  back_static:
    driver: local
