services:
  back:
    env_file:
      - ./back/.env
    image: sistemapresenca-back:latest
    pull_policy: never
    volumes:
      - back_static:/app/staticfiles
      - ./docker/back_entrypoint.sh:/app/back_entrypoint.sh
      - ./db.sqlite3:/app/db.sqlite3
      - ./back/media:/app/media
    environment:
      - UV_PROJECT_ENVIRONMENT=/app/.venv
      - APP_VERSION=${APP_VERSION}

  front:
    image: sistemapresenca-front:latest
    pull_policy: never
    volumes:
      - ./front_build:/mnt/front
    depends_on:
      - back


  caddy:
    image: caddy:latest
    depends_on:
      back:
        condition: service_started
      front:
        condition: service_started
    ports:
      - "80:80"
      - "443:443"
      - "8000:8000"
      - "3000:3000"
    volumes:
      - ./docker/Caddyfile:/etc/caddy/Caddyfile
      - back_static:/app/staticfiles
      - ./back/media:/app/media
      - ./front_build:/app/front

volumes:
  back_static:
    driver: local
