FROM ghcr.io/astral-sh/uv:alpine
WORKDIR /app

RUN apk add --no-cache tzdata

COPY pyproject.toml uv.lock /app/
RUN uv sync

COPY . /app

ENV VIRTUAL_ENV=/app/.venv
ENV PATH="/app/.venv/bin:$PATH"

EXPOSE 8000
ENTRYPOINT ["/app/back_entrypoint.sh"]
