FROM oven/bun:latest AS build

WORKDIR /app

COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

COPY . .
ARG VITE_APP_VERSION=UNKNOWN
RUN bun run build

FROM alpine:latest


COPY --from=build /app/build /app/front
CMD ["sh", "-c", "cp -rf /app/front/. /mnt/front/ && tail -f /dev/null"]
