FROM ghcr.io/astral-sh/uv:alpine AS builder
WORKDIR /app

COPY pyproject.toml uv.lock /app/
RUN uv sync --frozen --no-dev --no-install-project

COPY . /app
RUN uv sync --frozen --no-dev


FROM python:3.12-alpine AS final
WORKDIR /app

RUN apk add --no-cache tzdata

COPY --from=builder /app/.venv /app/.venv
COPY --from=builder /app /app

ENV VIRTUAL_ENV=/app/.venv
ENV PATH="/app/.venv/bin:$PATH"

EXPOSE 8000
ENTRYPOINT ["/app/back_entrypoint.sh"]