# Generated by Django 6.0.3 on 2026-04-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0002_alter_code_used_alter_member_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
