# Generated by Django 6.0.3 on 2026-04-13 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presenca', '0002_alter_checkin_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkin',
            options={'verbose_name': 'Check-in'},
        ),
        migrations.AlterModelOptions(
            name='code',
            options={'verbose_name': 'Código'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Evento'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Membro'},
        ),
        migrations.AlterModelOptions(
            name='score',
            options={'verbose_name': 'Score'},
        ),
        migrations.AlterModelOptions(
            name='scoreboard',
            options={'verbose_name': 'Quadro de Pontuação', 'verbose_name_plural': 'Quadros de Pontuação'},
        ),
        migrations.AlterModelOptions(
            name='timescorerules',
            options={'verbose_name': 'Regra de pontuação', 'verbose_name_plural': 'Regras de pontuação'},
        ),
    ]
