# Generated by Django 6.0.3 on 2026-04-17 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.contrib.auth.models import User

from presenca.models import Member

def get_default_user(apps, schema_editor):
    members = Member.objects.all()

    for m in members:
        suffix = m.name.split()[-1].lower()
        if m.birthday:
            suffix = m.birthday.strftime("%d%m%Y")

        if m.user:
            continue

        new_user = User.objects.create(
            username=f"{m.name.replace(' ', '_').lower()}"
        )
        first_name = m.name.split()[0]
        new_user.set_password(first_name+suffix)
        m.user = new_user
        m.save()

class Migration(migrations.Migration):
    dependencies = [
        ('presenca', '0003_alter_checkin_options_alter_code_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(get_default_user)
    ]
