# Generated by Django 6.0.3 on 2026-04-17 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presenca', '0004_member_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='presenca.member'),
        ),
    ]
