# Generated by Django 6.0.3 on 2026-04-20 01:09

from django.db import migrations, models


# Esta migração carregava um RunPython que normalizava usernames e criava
# senhas padrão para os usuários existentes, importando fix_passwords do
# management command set_default_passwords. A correção de dados já rodou em
# produção e em banco novo não há usuários para corrigir, então a operação
# foi removida para que o command possa mudar sem quebrar o migrate.
class Migration(migrations.Migration):

    dependencies = [
        ('presenca', '0005_alter_checkin_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='images/members/'),
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('board', 'member')},
        ),
    ]
