# Generated by Django 6.0.3 on 2026-04-20 01:09

from django.db import migrations, models
from unidecode import unidecode

from presenca.management.commands.set_default_passwords import fix_passwords


def fix_usernames(apps, schema_editor):
    Member = apps.get_model('presenca', 'Member')
    for member in Member.objects.all():
        user = member.user
        if user:
            pieces = user.username.split("_")
            new_pieces = [piece for piece in pieces if len(piece) > 3]
            new_username = unidecode("_".join(new_pieces[:2]))
            user.username = new_username
            user.save()

    fix_passwords(apps.get_model('auth', 'User'))

class Migration(migrations.Migration):

    dependencies = [
        ('presenca', '0005_alter_checkin_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='images/members/'),
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('board', 'member')},
        ),
        migrations.RunPython(fix_usernames),
    ]
