# Generated by Django 6.0.3 on 2026-04-20 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presenca', '0005_alter_checkin_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='images/members/'),
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('board', 'member')},
        ),
    ]
