# Generated by Django 6.0.3 on 2026-04-26 13:38

import django.db.models.deletion
from django.db import migrations, models


def set_default_event(apps, schema_editor):
    CheckIn = apps.get_model('presenca', 'CheckIn')
    Event = apps.get_model('presenca', 'Event')
    default_event, _ = Event.objects.get_or_create(name="Escola Sabatina")
    CheckIn.objects.filter(event__isnull=True).update(event=default_event)

class Migration(migrations.Migration):
    dependencies = [
        ('presenca', '0006_member_photo_alter_score_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='presenca.event'),
        ),
        migrations.RunPython(set_default_event, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='checkin',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presenca.event'),
        ),
    ]
