# Generated by Django 6.0.3 on 2026-04-26 16:42

from django.db import migrations, models

def fix_used_field(apps, schema_editor):
    Code = apps.get_model('presenca', 'Code')
    for code in Code.objects.all():
        code.used = code.updated_at
        code.save()

class Migration(migrations.Migration):
    dependencies = [
        ('presenca', '0007_checkin_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='used',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(fix_used_field),
    ]
