# Generated by Django 6.0.3 on 2026-04-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presenca', '0008_alter_code_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterUniqueTogether(
            name='checkin',
            unique_together={('member', 'date', 'event')},
        ),
    ]
