# Generated by Django 6.0.3 on 2026-07-18 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presenca', '0011_configs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='used',
        ),
        migrations.RemoveField(
            model_name='code',
            name='used_by',
        ),
    ]
