# Generated by Django 6.0.3 on 2026-09-11 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presenca', '0014_seed_code_rotation_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(blank=True, help_text="Como identificar o aparelho: 'tablet da recepção', por exemplo.", max_length=100, verbose_name='Apelido')),
                ('activated_at', models.DateTimeField(blank=True, help_text='Preenchido quando o aparelho lê o QR. Uso único.', null=True, verbose_name='Ativado em')),
                ('revoked_at', models.DateTimeField(blank=True, help_text='Corta o acesso do aparelho imediatamente.', null=True, verbose_name='Revogado em')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presenca.event')),
            ],
            options={
                'verbose_name': 'Dispositivo',
            },
        ),
    ]
